[versions]
lombok = "1.18.30"
dagger = "2.55"
junit = "4.13.2"
jetbrains-annotations = "26.0.2"

[libraries]
# Common
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }

# Annotations
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }

#Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
